### ISSUE TITLE
discord.token was not found in the config

### ISSUE THREAD

**Issue by Unbeccable** [Riku32/DiscordLink#9] opened 2021-07-12 15:30 UTC
**Describe the bug**
it may not be reading my token not too sure why it isnt though

**To Reproduce**
token being longer then certain digits makes it not work

**Expected behavior**
a hopeful bot with a bunch of people screaming in my discord server

**Screenshots**
![image](https://user-images.githubusercontent.com/87321465/125314818-27111900-e2fc-11eb-8c87-0d982c1fa188.png)

**Additional context**
where is says there isnt a token in the screenshot, there is.

**Comment by JSH32** [comment] 2021-07-12 23:57
Make sure there is a space between the `:` and the token/options. This is a common problem people don't often realize

**Comment by crazyaccess** [comment] 2021-07-13 09:50
@Unbeccable make it more clear on how to reproduce
i mean that doesn't give any info non the less . . .

**Comment by JSH32** [comment] 2021-07-13 18:39
@Unbeccable Show an example of your config but replace the fields like token and webhook with some random stuff just to show what your general config looks like.

**Comment by crazyaccess** [comment] 2021-07-14 03:11
Or rather keep the token and regenerate on the disocrd dev page

**Comment by Minikiin** [comment] 2021-07-20 21:04
Having the same issue.

This is my config (replaced some characters and shortened the other id's but you get the point)
```
discord:
  token: 0DY3MTI2OTM1MjEyMgkyNDU4.YPck4w.x1PvndgTg0frandomcharacters
  server_id: 5819
  owner_id: 1532
```

**Comment by JSH32** [comment] 2021-07-20 21:06
Can you change some numbers and send the whole file, I need to verify something

**Comment by Minikiin** [comment] 2021-07-20 21:13
> 
> 
> Can you change some numbers and send the whole file, I need to verify something

[config in here.zip](https://github.com/Riku32/DiscordLink/files/6851263/config.in.here.zip)

**Comment by JSH32** [comment] 2021-07-20 21:19
The file was not able to parse properly because of this 
```yml
  crosschat:
    enabled: true

    # This channel ID must be in the specified server_id server
    channel_id:8671425

    # This webhook CAN be a different channel than channel_id but SHOULDN'T
    # If it is different messages will not be relayed in the same place
    webhook:https://discord.com/api/webhooks/8671erasedhere
```
The whole file has to be formatted properly with spaces after the `:`. Otherwise it wont be treated properly by the config parser. So add those spaces and it should work.

**Comment by Minikiin** [comment] 2021-07-20 21:22
> 
> 
> The file was not able to parse properly because of this
> 
> ```yaml
>   crosschat:
>     enabled: true
> 
>     # This channel ID must be in the specified server_id server
>     channel_id:8671425
> 
>     # This webhook CAN be a different channel than channel_id but SHOULDN'T
>     # If it is different messages will not be relayed in the same place
>     webhook:https://discord.com/api/webhooks/8671erasedhere
> ```
> 
> The whole file has to be formatted properly with spaces after the `:`. Otherwise it wont be treated properly by the config parser. So add those spaces and it should work.

Omg I'm dumb I fixed it for the top id's but forgot to fix those. Thanks.

**Comment by JSH32** [comment] 2021-07-20 22:15
Aite while I'm here ill close this issue since I assume the @Unbeccable fixed it.

**Closed as completed by JSH32** 2021-07-20 22:15 UTC
Labels: question
